// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Herald
Cheops telegram chat groups notifier


    Schemes:
      http
    Host: herald.sirius.online
    BasePath: /api/v1/
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
