// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Cheops telegram chat groups notifier",
    "title": "Herald",
    "version": "0.0.1"
  },
  "host": "herald.sirius.online",
  "basePath": "/api/v1/",
  "paths": {
    "/chats": {
      "get": {
        "tags": [
          "chat"
        ],
        "operationId": "List",
        "responses": {
          "200": {
            "description": "Chat list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Something went wrang",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unxpected Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/messages/{chatName}": {
      "post": {
        "tags": [
          "message"
        ],
        "operationId": "Create",
        "parameters": [
          {
            "name": "message",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          {
            "type": "string",
            "name": "chatName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Message Created",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Something went wrang",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unxpected Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Chat": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true,
          "example": -12345678
        },
        "name": {
          "type": "string",
          "readOnly": true,
          "example": "test-group-chat"
        },
        "token": {
          "type": "string",
          "readOnly": true,
          "example": "12345678:AAEPflbLLeLgrBX-LDts0dqgjWh9x4PVwYc"
        }
      }
    },
    "Message": {
      "type": "object",
      "required": [
        "body"
      ],
      "properties": {
        "body": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true,
          "example": -12345678
        },
        "kind": {
          "type": "string",
          "default": "markdown"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Cheops telegram chat groups notifier",
    "title": "Herald",
    "version": "0.0.1"
  },
  "host": "herald.sirius.online",
  "basePath": "/api/v1/",
  "paths": {
    "/chats": {
      "get": {
        "tags": [
          "chat"
        ],
        "operationId": "List",
        "responses": {
          "200": {
            "description": "Chat list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Something went wrang",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unxpected Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/messages/{chatName}": {
      "post": {
        "tags": [
          "message"
        ],
        "operationId": "Create",
        "parameters": [
          {
            "name": "message",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          {
            "type": "string",
            "name": "chatName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Message Created",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Something went wrang",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unxpected Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Chat": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true,
          "example": -12345678
        },
        "name": {
          "type": "string",
          "readOnly": true,
          "example": "test-group-chat"
        },
        "token": {
          "type": "string",
          "readOnly": true,
          "example": "12345678:AAEPflbLLeLgrBX-LDts0dqgjWh9x4PVwYc"
        }
      }
    },
    "Message": {
      "type": "object",
      "required": [
        "body"
      ],
      "properties": {
        "body": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true,
          "example": -12345678
        },
        "kind": {
          "type": "string",
          "default": "markdown"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
